# Generated by Django 5.1.2 on 2024-11-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('postagens', models.ManyToManyField(to='postagens.postagem')),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
